name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18', '19', '20', '21' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - run: npm test
        env:
          CP_CLIENT_ID: ${{secrets.CP_CLIENT_ID}}
          CP_MERCHANT_ID: ${{secrets.CP_MERCHANT_ID}}
          CP_LICENCE_KEY: ${{secrets.CP_LICENCE_KEY}}
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          CP_CLIENT_ID: ${{secrets.CP_CLIENT_ID}}
          CP_MERCHANT_ID: ${{secrets.CP_MERCHANT_ID}}
          CP_LICENCE_KEY: ${{secrets.CP_LICENCE_KEY}}
